### ISSUE TITLE
opera flash player detection

### ISSUE THREAD

**Issue by jonhoo** [iye/lightsOn#10]
would be much appreciated.
Should be relatively straightforward, but unfortunately I don't have the time to sit down and do it at the moment. It will probably be similar to the Firefox one. The wrapper process looks like this:

```
/usr/lib/opera/pluginwrapper/operapluginwrapper-native -multiproc 2,0.1.8,7,133,153 -logfolder /home/user/.opera/logs/ -type native
```

**Comment by iye** [comment]
Sorry I didn't reply before. I have been busy with a new job. I read Opera was making a lot of changes and as I don't use it wasn't that interested in adding support for it. Have you tried latest versions of Opera? Can you update the process name that use flash? Be sure to have a flash running in your browser when you do ps.

**Comment by jonhoo** [comment]
Yeah, it's probably not worth making any changes for Opera atm until they release the new Blink-based browser. I'll close this for now.
