### ISSUE TITLE
why check for fullscreen ?

### ISSUE THREAD

**Issue by solsticedhiver** [iye/lightsOn#18]
hi.
I don't see the point of checking if the windows is full screen or not.
If you are watching a video on youtube in your browser whether it is in fullscreen or not does not matter as in either case you don't want the screensaver to kick in.

the same is true for vlc or mplayer

EDIT: Ok: it's because you can't check if the player is actually playing a video or not ? right ?

**Comment by iye** [comment]
There's no way to know from console if a flash video is playing. Usually (at least in my case) if you are watching a long video you would use fullscreen and then it's posible to detect flash because the topmost window name can be retrieved from console. If you know some other method you are welcomed.

solsticedhiver notifications@github.com wrote:

> hi.
> I don't see the point of checking if the windows is full screen or not.
> If you are watching a video on youtube in your browser whether it is in
> fullscreen or not does not matter as in either case you don't want the
> screensaver to kick in.
> 
> the same is true for vlc or mplayer
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/iye/lightsOn/issues/18

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by solsticedhiver** [comment]
as your script was not working for me on ubuntu with chromium and pepper flash, I changed it to use 

  if [[ `pgrep -lfc "/usr/lib/chromium-browser/chromium-browser --type=ppapi --channel="` -ge 1 ]]

and deactivating the full screen check. 

and it works even if the flash video is not full screen.

**Comment by iye** [comment]
now maybe if you left your pc with with your browser running your screensaver will not activate

solsticedhiver notifications@github.com wrote:

> as your script was not working for me on ubuntuwith chromium and pepper
> flash, I changed it to use 
> if [[ `pgrep -lfc "/usr/lib/chromium-browser/chromium-browser
> --type=ppapi --channel="` -ge 1 ]]
> 
> and deactivating the full screen check. 
> 
> and it works even if the flash video is not full screen.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/iye/lightsOn/issues/18#issuecomment-33291238

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
