### ISSUE TITLE
Arch Linux, or maybe new flash version issue

### ISSUE THREAD

**Issue by tomashejatko** [iye/lightsOn#2]
Hello,
when i work with :
Name           : flashplugin
Version        : 11.1.102.55-1
in Arch Linux, your script didn't worked, i've started to analyze, and problem was, that :
$activ_win_title for flash player plugin had value  : **WM_CLASS(STRING) = "plugin-container", "Plugin-container"**, so I easily edited a line to look like :
...
    if [ $firefox_flash_detection == 1 ];then
        if [[ "$activ_win_title" = _plugin-cont_ ]];then
        # Check if plugin-container process is running
...
Do i have to commit a patch? Or is it Arch Linux related somehow? If it's even real. Dunno much about X-related things

**Comment by iye** [comment]
Older versions of Flash didn't reported WM_CLASS(STRING) so it appeared as **unknown**.
Will try to fix it tonight. Thanks for reporting the issue.

**Comment by tomashejatko** [comment]
It's just about
 if [[ "$activ_win_title" = plugin-cont ]];then
line. And you're welcome, your script solved last issue with openbox for me :)

**Comment by iye** [comment]
maybe better:
 if [[ "$activ_win_title" = _unknown_ || "$activ_win_title" = _plugin-container_]];then   

so that way it works with other versions of flash. Mine still has WM_CLASS(STRING) = " unknown ", " unknown "

**Comment by tomashejatko** [comment]
yeah, agree ;)

**Comment by iye** [comment]
I updated master branch, want to give it a try and report back?

**Comment by tomashejatko** [comment]
Of course, i'll make it tonight :)

**Comment by tomashejatko** [comment]
It's fine, works great for me :)
