### ISSUE TITLE
xprop returns: _NET_ACTIVE_WINDOW:  not found.

### ISSUE THREAD

**Issue by SuperFluffy** [iye/lightsOn#7]
Trying to run `lightsOn.sh` in my xmonad setup, the script fails for me. I have tried to investigate where the problem comes from, and it seems to be coming from `xprop` (currently line 64).

Here is a little rundown of where I think the problems crops up.

```
$ display=xvinfo | sed -n 's/^screen #\([0-9]\+\)$/\1/p'                                        
0
$ DISPLAY=:0.${display} xprop -root _NET_ACTIVE_WINDOW
_NET_ACTIVE_WINDOW:  not found.
```

Since apparently `_NET_ACTIVE_WINDOW` doesn't exist (I wonder why?), everything thereafter fails as well. and we get for:

```
isActivWinFullscreen=`DISPLAY=:0.${display} xprop -id $activ_win_id | grep _NET_WM_STATE_FULLSCREEN`
```

```
sage:  xprop [-options ...] [[format [dformat]] atom] ...

where options include:
    -grammar                       print out full grammar for command line
    -display host:dpy              the X server to contact
    -id id                         resource id of window to examine
    -name name                     name of window to examine
    -font name                     name of font to examine
    -remove propname               remove a property
    -set propname value            set a property to a given value
    -root                          examine the root window
    -len n                         display at most n bytes of any property
    -notype                        do not display the type field
    -fs filename                   where to look for formats for properties
    -frame                         don't ignore window manager frames
    -f propname format [dformat]   formats to use for property of given name
    -spy 
```

Since I don't know if it is imporant, but I start my X session with:

```
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
```

Any ideas how to fix this? I would really love to use `lightsOn`!

**Comment by iye** [comment]
I'm not familiar with Xmonad, but check this: https://code.google.com/p/xmonad/issues/detail?id=520

**Comment by iye** [comment]
I haven't researched this issue enough but as the post said, lightsOn should be checking for EWMH support. Anyway even if it checked, it should provide detection for the active window in some other way. Don't know how right now. Remember this is a bash script and I try lightsOn not to require you to install extra packages.

If I were you I would try the XMonad.Hooks.EwmhDesktops thing mentioned in the link above.

**Comment by SuperFluffy** [comment]
You were absolutely right! hank you for searching this. I have my config use `ewmh` now, and I get

```
& DISPLAY=:0.0 xprop -root NET_ACTIVE_WINDOW 

_NET_ACTIVE_WINDOW(WINDOW): window id # 0x1e00003
```

As needed! :)
